### ISSUE TITLE
gluu-server_2.3.4-1_amd64.deb Ubuntu 14.10 installation error

### ISSUE THREAD

**Issue by dmogn** [GluuFederation/debpackages#1]
Upgrade from installed gluu-server 2.3.3-1 to 2.3.4-1:
# dpkg -i /home/sirius/Downloads/Java/gluu-server_2.3.4-1_amd64.deb

(Reading database ... 670821 files and directories currently installed.)
Preparing to unpack .../gluu-server_2.3.4-1_amd64.deb ...
Checking if Gluu Server is running in order to do backup...
Created backup with OpenDJ DB in folder /opt/gluu-server.bkp/09_16_2015_18:09:59
Checking to make sure Gluu Server is down...
Prerm called with unknown argument 'upgrade'
Unpacking gluu-server (2.3.4-1) over (2.3.3-1) ...
Your changes will be saved into /opt/gluu-server.saved
Setting up gluu-server (2.3.4-1) ...
dpkg: error processing package gluu-server (--install):
 subprocess installed post-installation script returned error exit status 125
Processing triggers for ureadahead (0.100.0-16) ...
ureadahead will be reprofiled on next reboot
Errors were encountered while processing:
 gluu-server
#

**Comment by dmogn** [comment]
Update: I don't sure that it is bug of gluu-server_2.3.4-1_amd64.deb
 My 2.3.3-1 installation steels runned after service stop. 2.3.3-1 has been uninstalled OK after reboot.
2.3.4-1 installation and setup procedure from zero, 2.3.4-1 uninstallation: All Ok.

**Comment by nynymike** [comment]
Thanks for the feedback dmitry. I was sort of skeptical of the upgrade process myself...

**Comment by dmogn** [comment]
I have reproduced the upgrade bug with clean server settings:
- Install gluu-server_2.3.3-1_amd64.deb
- Basic server setup ( ./setup.py )
- # service gluu-server stop
- Check that all proceses really exited in OS.
- Install gluu-server_2.3.3-1_amd64.deb (dpkg -i /home/sirius/Downloads/Java/gluu-server_2.3.4-1_amd64.deb)
- Error repeated:
dpkg: error processing package gluu-server (--install):
 subprocess installed post-installation script returned error exit status 125
Processing triggers for ureadahead (0.100.0-16) ...

**Comment by dmogn** [comment]
Obsolete
